mooncalendar/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name="mooncalendar"
urlpatterns = [
    path("", views.index, name="index"),
    path("events/", views.CalendarEventListView.as_view(), name="calendarevent-list"),
    path("new-event/", views.CalendarEventCreateView.as_view(), name="calendarevent-create"),
    path("<slug:pk>/", views.CalendarEventDetailView.as_view(), name="calendarevent-detail"),
    path("<slug:pk>/update", views.CalendarEventUpdateView.as_view(), name="calendarevent-update"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('mooncal/', include("mooncalendar.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        *urlpatterns,
    ]

mooncalendar/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q, CheckConstraint

class CalendarEvent(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)

    class Meta:
        constraints = [
            CheckConstraint(check=~Q(title=""), name="calendar_event_title_not_empty")
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("mooncalendar:calendarevent-detail", kwargs={"pk": self.pk})

mooncalendar/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.views import generic

from .models import CalendarEvent

def index(request):
    return render(request, "mooncalendar/index.html")
    
class CalendarEventListView(generic.ListView):
    model = CalendarEvent
    paginate_by = 10

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return super().get_queryset().order_by('-id')

class CalendarEventCreateView(generic.CreateView):
    model = CalendarEvent
    fields = ["title"]

class CalendarEventDetailView(generic.DetailView):
    model = CalendarEvent
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class CalendarEventUpdateView(generic.UpdateView):
    model = CalendarEvent
    fields = ["title"]
    template_name_suffix = "_update_form"

mooncalendar/templates/mooncalendar/calendarevent_detail.html
<h1>
    {{ object.title }}
    <a href="{% url 'mooncalendar:calendarevent-update' object.pk %}">Edit</a>
</h1>

mooncalendar/templates/mooncalendar/calendarevent_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

mooncalendar/templates/mooncalendar/calendarevent_list.html
<h1>Calendar Events</h1>
<ul>
{% for calendar_event in object_list %}
    <li><a href="{% url 'mooncalendar:calendarevent-detail' calendar_event.pk %}">{{ calendar_event.title }}</a></li>
{% empty %}
    <li>No calendar events yet.</li>
{% endfor %}
</ul>
<a href="{% url 'mooncalendar:calendarevent-create' %}">Create an event</a>

mooncalendar/templates/mooncalendar/calendarevent_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

mooncalendar/templates/mooncalendar/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'mooncalendar/style.css' %}">
<h1>Welcome to Moon Calendars!</h1>
<p><a href="events/">View some of the latest events</a></p>
<p><a href="{% url 'mooncalendar:calendarevent-create' %}">Create an event</a></p>